// Generated by Cypress Author on 2026-08-04.

/**
 * Surveyz (UAT) login flow.
 *
 * Credentials are read at run time rather than committed. This project sets
 * `allowCypressEnv: false` in cypress.config.js, which makes the legacy
 * `Cypress.env()` API throw, so `cy.env()` is the supported replacement.
 *
 * Provide them either as environment variables:
 *   CYPRESS_TEST_USER='...' CYPRESS_TEST_PASS='...' npx cypress run
 * or in the git-ignored cypress.env.json:
 *   { "TEST_USER": "...", "TEST_PASS": "..." }
 *
 * Note: the backend is served from Australia. The client-side country check is
 * stubbed below, but the API itself may still require an AU egress IP.
 */

// Real `data-cy` hooks rendered by the login page — the Ionic wrappers place
// them on the component root, so the native control is a descendant.
const EMAIL_FIELD = '[data-cy="email-input"]';
const PASSWORD_FIELD = '[data-cy="password-input"]';
const LOGIN_BUTTON = '[data-cy="login"]';

describe("Login", () => {
  beforeEach(() => {
    // Aliases are defined per test — Cypress clears them between tests.
    cy.env(["TEST_USER", "TEST_PASS"]).as("credentials");

    // The app geo-blocks non-AU traffic with an undismissable modal based on
    // this lookup. Stub it so the result never depends on the runner's IP.
    cy.intercept("GET", "https://ipapi.co/country/", {
      statusCode: 200,
      body: "AU",
    }).as("countryLookup");

    // Every operation shares one GraphQL endpoint, so alias only the login
    // mutation. Waiting on it removes any need for an arbitrary cy.wait().
    cy.intercept("POST", "**/graphql", (req) => {
      if (req.body?.query?.includes("login(email:")) {
        req.alias = "loginRequest";
      }
    });

    cy.visit("/login");
  });

  it("submits valid credentials → lands on the dashboard with account info in the header", () => {
    cy.get("@credentials").then(({ TEST_USER, TEST_PASS }) => {
      // Fail with a clear message instead of typing `undefined` into the form.
      expect(TEST_USER, "TEST_USER env var").to.be.a("string").and.not.be.empty;
      expect(TEST_PASS, "TEST_PASS env var").to.be.a("string").and.not.be.empty;

      // `includeShadowDom` (cypress.config.js) lets .find() reach the native
      // input inside Ionic's <ion-input> shadow root. Blurring runs the field
      // validator immediately rather than waiting out the 800ms input debounce.
      cy.get(EMAIL_FIELD).find("input").type(TEST_USER).blur();
      cy.get(PASSWORD_FIELD)
        .find("input")
        .type(TEST_PASS, { log: false })
        .blur();
    });

    // The button stays disabled until both fields validate, so let the
    // assertion retry rather than clicking into a disabled control.
    cy.get(LOGIN_BUTTON).find("button").should("be.enabled").click();

    cy.wait("@loginRequest").its("response.statusCode").should("eq", 200);

    // Login hops through /login-success before settling on the dashboard, so
    // allow more than the default timeout for the round trip plus redirect.
    cy.location("pathname", { timeout: 20000 }).should("eq", "/dashboard/home");

    cy.get("ion-header").within(() => {
      // The header greets the signed-in member by first name: "Hi, <name> 👋".
      cy.contains(/^Hi, .+/).should("be.visible");

      // Wallet balance. No data-cy hook exists here — worth adding one to the
      // Header component so this stops depending on a styling class.
      cy.get(".ft-balance-outline").should("be.visible");
    });

    // The authenticated shell (tab bar / side menu) replaced the login screen.
    cy.get('[data-cy="home"]').should("exist");
  });
});
